openapi: 3.1.0
info:
  version: 0.0.0
  title: Power Play API
  description: Developer documentation for the PowerPlay app
  license:
    name: MIT
    url: https://opensource.org/license/mit

paths:
  # /[URL path]
  #$ref: "./[Relative path starting from v1]#/paths/[yml path]"
  /auth:
    $ref: "./auth/auth.yml#/paths/auth"
  /games:
    $ref: "./sports/components/games.yml#/paths/~1games"
  /games/{gameId}:
    $ref: "./sports/components/games.yml#/paths/~1games~1{gameId}"
  /goals:
    $ref: "./sports/stats/goals.yml#/paths/goals"
  /leagues:
    $ref: "./sports/components/leagues.yml#/paths/leagues"
  /logos:
    $ref: "./sports/components/logos.yml#/paths/~1logos"
  /logos/{id}:
    $ref: "./sports/components/logos.yml#/paths/~1logos~1%7Bid%7D"
  /penalties:
    $ref: "./sports/stats/penalties.yml#/paths/penalties"
  /penaltyTypes:
    $ref: "./sports/stats/penalties.yml#/paths/penaltyTypes"
  /rosters:
    $ref: "./sports/components/rosters.yml#/paths/rosters"
  /seasons:
    $ref: "./sports/components/seasons.yml#/paths/seasons"
  /shotsongoal:
    $ref: "./sports/stats/shotsongoal.yml#/paths/shotsOnGoal"
  /teams:
    $ref: "./sports/components/teams.yml#/paths/~1teams"
  /teams/{id}:
    $ref: "./sports/components/teams.yml#/paths/~1teams~1%7Bid%7D"
  /user:
    $ref: "./users/users.yml#/paths/user"
  /venues:
    $ref: "./sports/stats/venues.yml#/paths/venues"
  
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
