// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package components

import (
	"github.com/jak103/powerplay/internal/models"
	"sync"
)

// Ensure, that sessionMock does implement session.
// If this is not the case, regenerate this file with moq.
var _ session = &sessionMock{}

// sessionMock is a mock implementation of session.
//
//	func TestSomethingThatUsessession(t *testing.T) {
//
//		// make and configure a mocked session
//		mockedsession := &sessionMock{
//			GetGoalsFunc: func() ([]models.Goal, error) {
//				panic("mock out the GetGoals method")
//			},
//			SaveGoalFunc: func(goal *models.Goal) (*models.Goal, error) {
//				panic("mock out the SaveGoal method")
//			},
//		}
//
//		// use mockedsession in code that requires session
//		// and then make assertions.
//
//	}
type sessionMock struct {
	// GetGoalsFunc mocks the GetGoals method.
	GetSeasonsFunc func() ([]models.Season, error)

	// SaveGoalFunc mocks the SaveGoal method.
	CreateSeasonFunc func(goal *models.Season) (*models.Season, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetGoals holds details about calls to the GetGoals method.
		GetSeasons []struct {
		}
		// SaveGoal holds details about calls to the SaveGoal method.
		CreateSeason []struct {
			// Goal is the goal argument value.
			Season *models.Season
		}
	}
	lockGetSeasons sync.RWMutex
	lockCreateSeason sync.RWMutex
}

// GetGoals calls GetGoalsFunc.
func (mock *sessionMock) GetSeasons() ([]models.Season, error) {
	if mock.GetSeasonsFunc == nil {
		panic("sessionMock.GetGoalsFunc: method is nil but session.GetGoals was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetSeasons.Lock()
	mock.calls.GetSeasons = append(mock.calls.GetSeasons, callInfo)
	mock.lockGetSeasons.Unlock()
	return mock.GetSeasonsFunc()
}

// GetGoalsCalls gets all the calls that were made to GetGoals.
// Check the length with:
//
//	len(mockedsession.GetGoalsCalls())
func (mock *sessionMock) GetSeasonsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetSeasons.RLock()
	calls = mock.calls.GetSeasons
	mock.lockGetSeasons.RUnlock()
	return calls
}

// SaveGoal calls SaveGoalFunc.
func (mock *sessionMock) CreateSeason(season *models.Season) (*models.Season, error) {
	if mock.CreateSeasonFunc == nil {
		panic("sessionMock.SaveGoalFunc: method is nil but session.SaveGoal was just called")
	}
	callInfo := struct {
		Season *models.Season
	}{
		Season: season,
	}
	mock.lockCreateSeason.Lock()
	mock.calls.CreateSeason = append(mock.calls.CreateSeason, callInfo)
	mock.lockCreateSeason.Unlock()
	return mock.CreateSeasonFunc(season)
}

// SaveGoalCalls gets all the calls that were made to SaveGoal.
// Check the length with:
//
//	len(mockedsession.SaveGoalCalls())
func (mock *sessionMock) CreateSeasonCalls() []struct {
	Season *models.Season
} {
	var calls []struct {
		Season *models.Season
	}
	mock.lockCreateSeason.RLock()
	calls = mock.calls.CreateSeason
	mock.lockCreateSeason.RUnlock()
	return calls
}
